# Required
labels:
  - label: "ê°„ë‹¨í•´ìš”"
    limit: 10
  - label: 'ê°€ë²¼ì›Œìš”' 
    limit: 30
  - label: 'ë§Œë§Œí•´ìš”'
    limit: 100
  - label: 'í• ë§Œí•´ìš”'
    limit: 300
  - label: 'ë„ì „í•´ìš”'
    limit: 500
  - label: 'ìš©ê¸°ë‚´ìš”'
    limit: 1000

# Optional
max-size-message:
  "1000ì¤„ì´ ë„˜ëŠ” ë³€ê²½ì ì´ ìƒê¸´ PRì…ë‹ˆë‹¤!\në‘ ê°œ ì´ìƒì˜ PRë¡œ ë¶„ë¦¬í•˜ëŠ” ê±¸ ì œì•ˆë“œë ¤ìš”.\në¦¬ë·°ì–´ëŠ” ì •ì‹  ê±´ê°•ì„ ì§€í‚¬ ìˆ˜ ìˆê³ , ë¦¬ë·°ì´ëŠ” ë” ì¢‹ì€ í’ˆì§ˆì˜ ë¦¬ë·°ë¥¼ ë°›ì•„ë³¼ ìˆ˜ ìˆì–´ìš” ğŸ¥°"

# Optional
ignore-file-patterns:
  - /package-lock.json/
  - /yarn.lock/
  - /\.(svg)$/